# 运行端口
server:
  port: 10010

mybatis:
  typeAliasesPackage: com.cn.rmq.sample.model.po
  mapperLocations: classpath:com/cn/rmq/sample/mapper/*.xml

spring:
  # 数据库连接配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/reliable-message-sample?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  # ActiveMQ配置
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin

# Dubbo配置
dubbo:
  application:
    name: spring-boot-sample
    logger: slf4j
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20882
  scan:
    base-packages: com.cn.rmq.sample.service.impl